[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Stephen Waits <swaits@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
once_cell = "1.5.2"
peg = "0.6.3"
regex = "1"